"""
Jenkins configuration MCP resources.

Provides access to Jenkins configuration data through MCP resources.
"""

import structlog

logger = structlog.get_logger()


async def get_system_config() -> str:
    """Get Jenkins system configuration."""
    try:
        from ..server import get_jenkins_client
        client = get_jenkins_client()

        system_info = await client.get_system_info(include_stats=False)

        config_data = {
            "mode": system_info.get("mode", "NORMAL"),
            "node_description": system_info.get("nodeDescription", ""),
            "num_executors": system_info.get("numExecutors", 0),
            "use_crumbs": system_info.get("useCrumbs", False),
            "use_security": system_info.get("useSecurity", False),
            "system_message": system_info.get("systemMessage", ""),
            "slave_agent_port": system_info.get("slaveAgentPort", 0),
            "quieting_down": system_info.get("quietingDown", False)
        }

        return f"""# Jenkins System Configuration

## Basic Settings
- **Mode**: {config_data['mode']}
- **Node Description**: {config_data['node_description']}
- **Number of Executors**: {config_data['num_executors']}
- **Slave Agent Port**: {config_data['slave_agent_port']}

## Security Settings
- **Use Security**: {config_data['use_security']}
- **Use Crumbs**: {config_data['use_crumbs']}

## Status
- **Quieting Down**: {config_data['quieting_down']}
- **System Message**: {config_data['system_message']}

Generated by Jenkins MCP Server
"""

    except Exception as e:
        logger.error("failed_to_get_system_config", error=str(e))
        return f"Error retrieving system configuration: {str(e)}"


async def get_job_config(job_name: str) -> str:
    """Get Jenkins job configuration."""
    try:
        from ..server import get_jenkins_client
        client = get_jenkins_client()

        config_result = await client.get_job_config(job_name=job_name, format="xml")
        config_xml = config_result.get("config_xml", "")

        return f"""# Job Configuration: {job_name}

## XML Configuration
```xml
{config_xml}
```

Generated by Jenkins MCP Server
"""

    except Exception as e:
        logger.error("failed_to_get_job_config", job_name=job_name, error=str(e))
        return f"Error retrieving job configuration for '{job_name}': {str(e)}"


async def get_view_config(view_name: str) -> str:
    """Get Jenkins view configuration."""
    try:
        from ..server import get_jenkins_client
        client = get_jenkins_client()

        view_details = await client.get_view_details(view_name=view_name)

        return f"""# View Configuration: {view_name}

## View Details
- **Name**: {view_details.get('name', view_name)}
- **URL**: {view_details.get('url', 'Unknown')}
- **Description**: {view_details.get('description', 'No description')}
- **Type**: {view_details.get('class', 'Unknown')}

## Job Configuration
- **Jobs Count**: {len(view_details.get('jobs', []))}
- **Use Regex**: {view_details.get('useRegex', False)}
- **Include Regex**: {view_details.get('includeRegex', '')}

## Jobs in this View
{chr(10).join([f"- {job.get('name', 'Unknown')}" for job in view_details.get('jobs', [])])}

Generated by Jenkins MCP Server
"""

    except Exception as e:
        logger.error("failed_to_get_view_config", view_name=view_name, error=str(e))
        return f"Error retrieving view configuration for '{view_name}': {str(e)}"


async def get_node_config(node_name: str) -> str:
    """Get Jenkins node configuration."""
    try:
        from ..server import get_jenkins_client
        client = get_jenkins_client()

        node_details = await client.get_node_details(node_name=node_name)

        return f"""# Node Configuration: {node_name}

## Node Details
- **Display Name**: {node_details.get('displayName', node_name)}
- **URL**: {node_details.get('url', 'Unknown')}
- **Description**: {node_details.get('description', 'No description')}
- **Offline**: {node_details.get('offline', True)}
- **Idle**: {node_details.get('idle', True)}

## Configuration
- **Manual Launch Allowed**: {node_details.get('manualLaunchAllowed', False)}
- **Remote FS**: {node_details.get('remoteFS', 'Unknown')}
- **Labels**: {', '.join(node_details.get('labels', []))}
- **Mode**: {node_details.get('mode', 'NORMAL')}
- **Number of Executors**: {node_details.get('numExecutors', 0)}

Generated by Jenkins MCP Server
"""

    except Exception as e:
        logger.error("failed_to_get_node_config", node_name=node_name, error=str(e))
        return f"Error retrieving node configuration for '{node_name}': {str(e)}"