"""
Jenkins status MCP resources.

Provides access to Jenkins status data through MCP resources.
"""

import structlog

logger = structlog.get_logger()


async def get_system_status() -> str:
    """Get Jenkins system status."""
    try:
        from ..server import get_jenkins_client
        client = get_jenkins_client()

        system_info = await client.get_system_info(include_stats=True)
        queue_info = await client.get_build_queue()

        return f"""# Jenkins System Status

## System Information
- **Mode**: {system_info.get('mode', 'UNKNOWN')}
- **Description**: {system_info.get('description', 'Jenkins')}
- **URL**: {system_info.get('url', 'Unknown')}

## Executors
- **Total Executors**: {system_info.get('numExecutors', 0)}
- **Busy Executors**: {system_info.get('busyExecutors', 0)}

## Build Queue
- **Queue Length**: {len(queue_info.get('queue_items', []))}
- **Items in Queue**: {', '.join([item.get('job', {}).get('name', 'Unknown') for item in queue_info.get('queue_items', [])[:5]])}

Generated by Jenkins MCP Server
"""

    except Exception as e:
        logger.error("failed_to_get_system_status", error=str(e))
        return f"Error retrieving system status: {str(e)}"


async def get_job_status(job_name: str) -> str:
    """Get Jenkins job status."""
    try:
        from ..server import get_jenkins_client
        client = get_jenkins_client()

        job_details = await client.get_job_details(job_name=job_name)

        last_build = job_details.get("lastBuild", {})
        last_completed_build = job_details.get("lastCompletedBuild", {})

        return f"""# Job Status: {job_name}

## Job Information
- **Name**: {job_details.get('name', job_name)}
- **Display Name**: {job_details.get('displayName', job_name)}
- **URL**: {job_details.get('url', 'Unknown')}
- **Buildable**: {job_details.get('buildable', False)}
- **In Queue**: {job_details.get('inQueue', False)}
- **Concurrent Build**: {job_details.get('concurrentBuild', False)}

## Last Build
- **Number**: {last_build.get('number', 'N/A')}
- **Result**: {last_build.get('result', 'N/A')}
- **URL**: {last_build.get('url', 'N/A')}

## Last Completed Build
- **Number**: {last_completed_build.get('number', 'N/A')}
- **Result**: {last_completed_build.get('result', 'N/A')}
- **URL**: {last_completed_build.get('url', 'N/A')}

## Next Build Number
- **Next Build**: #{job_details.get('nextBuildNumber', 'N/A')}

Generated by Jenkins MCP Server
"""

    except Exception as e:
        logger.error("failed_to_get_job_status", job_name=job_name, error=str(e))
        return f"Error retrieving job status for '{job_name}': {str(e)}"


async def get_build_status(job_name: str, build_number: int) -> str:
    """Get Jenkins build status."""
    try:
        from ..server import get_jenkins_client
        client = get_jenkins_client()

        build_details = await client.get_build_details(job_name=job_name, build_number=build_number)

        return f"""# Build Status: {job_name} #{build_number}

## Build Information
- **Number**: {build_details.get('number', build_number)}
- **Result**: {build_details.get('result', 'UNKNOWN')}
- **URL**: {build_details.get('url', 'Unknown')}
- **Building**: {build_details.get('building', False)}

## Timing
- **Timestamp**: {build_details.get('timestamp', 0)}
- **Duration**: {build_details.get('duration', 0)} ms
- **Estimated Duration**: {build_details.get('estimatedDuration', 0)} ms

## Display Information
- **Display Name**: {build_details.get('displayName', f'#{build_number}')}
- **Full Display Name**: {build_details.get('fullDisplayName', f'{job_name} #{build_number}')}
- **Description**: {build_details.get('description', 'No description')}

Generated by Jenkins MCP Server
"""

    except Exception as e:
        logger.error("failed_to_get_build_status", job_name=job_name, build_number=build_number, error=str(e))
        return f"Error retrieving build status for '{job_name} #{build_number}': {str(e)}"


async def get_queue_status() -> str:
    """Get Jenkins build queue status."""
    try:
        from ..server import get_jenkins_client
        client = get_jenkins_client()

        queue_info = await client.get_build_queue()
        queue_items = queue_info.get('queue_items', [])

        return f"""# Build Queue Status

## Queue Summary
- **Total Items**: {len(queue_items)}
- **Status**: {'Active' if queue_items else 'Empty'}

## Queue Items
{chr(10).join([f"### {item.get('job', {}).get('name', 'Unknown Job')}" + chr(10) +
               f"- **ID**: {item.get('id', 'Unknown')}" + chr(10) +
               f"- **Why**: {item.get('why', 'Unknown reason')}" + chr(10) +
               f"- **Stuck**: {item.get('stuck', False)}" + chr(10) +
               f"- **Blocked**: {item.get('blocked', False)}" + chr(10) +
               f"- **Buildable**: {item.get('buildable', False)}" + chr(10) +
               f"- **Waiting**: {item.get('waiting', False)}"
               for item in queue_items[:10]])}

Generated by Jenkins MCP Server
"""

    except Exception as e:
        logger.error("failed_to_get_queue_status", error=str(e))
        return f"Error retrieving queue status: {str(e)}"


async def get_nodes_status() -> str:
    """Get Jenkins nodes status."""
    try:
        from ..server import get_jenkins_client
        client = get_jenkins_client()

        nodes_info = await client.list_nodes(include_details=True)
        nodes = nodes_info.get('nodes', [])

        return f"""# Nodes Status

## Summary
- **Total Nodes**: {nodes_info.get('total_count', 0)}
- **Online Nodes**: {nodes_info.get('online_count', 0)}
- **Offline Nodes**: {nodes_info.get('offline_count', 0)}

## Node Details
{chr(10).join([f"### {node.get('displayName', 'Unknown Node')}" + chr(10) +
               f"- **Status**: {'🟢 Online' if not node.get('offline', True) else '🔴 Offline'}" + chr(10) +
               f"- **Idle**: {'Yes' if node.get('idle', True) else 'No'}" + chr(10) +
               f"- **Executors**: {node.get('numExecutors', 0)}" + chr(10) +
               f"- **Description**: {node.get('description', 'No description')}" + chr(10) +
               f"- **URL**: {node.get('url', 'Unknown')}"
               for node in nodes])}

Generated by Jenkins MCP Server
"""

    except Exception as e:
        logger.error("failed_to_get_nodes_status", error=str(e))
        return f"Error retrieving nodes status: {str(e)}"